### ISSUE TITLE
Install fails on lets encrypt

### ISSUE THREAD

**Issue by cErikson** [elabftw/elabctl#16] opened 2018-12-05 01:07 UTC
I'm trying to install elab on a server. 
I've made a new user and add the user to sudo and gluster groups.
I run elabctl, and edit the config to point to a directory in the gluster mount. 
I run `elabctl install`, and accept all defaults.
The installer runs and exits with the following
```
Requesting to rerun ./letsencrypt-auto with root privileges...
Requested domain  is not a FQDN because it contains an empty label.
```
When I look for the files/dirs in the config, all I see is data. Which has letsencrypt  mysql  web in it.

**Comment by cErikson** [comment] 2018-12-05 01:20
Also, the previous screen output
```
/usr/local/bin/elabctl: line 342: ufw: command not found
/usr/local/bin/elabctl: line 344: ufw: command not found
```
I've installed uncomplicated firewall, it is only accessible to root, and reran the installation. It still can't find ufw, and fails with the previous message.

**Comment by NicolasCARPi** [comment] 2018-12-05 13:50
Hello,

The `ufw` bit is to make it easier for users installing it on a droplet, where port 443 is closed by default, it has no effect if the command is not found.

What domain are you feeding the script? Do you already have letsencrypt installed on this server? See: https://community.letsencrypt.org/t/requested-domain-is-not-a-fqdn-because-it-contains-an-empty-label/29464/7 and https://community.letsencrypt.org/t/requested-domain-is-not-a-fqdn-error/20952/3

**Comment by cErikson** [comment] 2018-12-05 18:44
The script never has asked me for a domain name.  The OS is a fresh install. However, When I first ran the git pull was interrupted during a version checkout. But I have completely deleted the repo in the data dir. And when I rerun the script git successfully pulls letsencrypt.

**Comment by cErikson** [comment] 2018-12-05 19:23
It seems for what ever reason the script skipped any dialog screen with a text entry. I tested dialog by running line 238, it was able to open a text entry and saved it to a variable.  I've now got elab installed by running the commands by hand from line 346.

**Comment by NicolasCARPi** [comment] 2018-12-06 13:48
That's interesting. Please prodive info on the OS.

**Comment by cErikson** [comment] 2018-12-07 02:04
*OS*
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch

Relatively fresh install of debian with baseos, coreutils and ssh selected. 


*Dialog*
Package: dialog
Version: 1.3-20160828-2
Installed-Size: 1111
Architecture: amd64
Filename: pool/main/d/dialog/dialog_1.3-20160828-2_amd64.deb
Size: 262390
MD5sum: 18dd617e2c7932592f4b898f6acd0874
SHA256: 0e3001de2f5f7cd7f06f39863bc3f1b0081d404eda611784fb36acf7d15694f2

**Comment by NicolasCARPi** [comment] 2018-12-09 01:50
Thanks, I'll see if I can reproduce later.

**Comment by NicolasCARPi** [comment] 2018-12-09 19:39
Ok, I just did a fresh install on Debian 9.6 with same version of dialog. No problems. You probably experienced a temporary network issue.

**Closed as completed by NicolasCARPi** 2018-12-09 19:39 UTC
Labels: support
